name: Publish

on:
  push:
    branches:
      - master

  release:
    types: [published]

  schedule:
    - cron: "*/5 * * * *"

env:
  IMAGE_NAME: codeql
  CONTAINER_REGISTRY_HOST: ghcr.io

jobs:
  schedule:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
    - uses: actions/checkout@v2

    - name: Get latest versions
      id: versions
      run: |
        CLI_RELEASE=$(curl https://api.github.com/repos/github/codeql-cli-binaries/releases/latest | jq -r '.tag_name')
        CURRENT_RELEASE=$(curl https://api.github.com/repos/nealfennimore/codeql-docker/releases/latest | jq -r '.tag_name')
        echo "::set-output name=cli::$CLI_RELEASE"
        echo "::set-output name=current::$CURRENT_RELEASE"
      shell: bash

    - name: Generate Codeql Cli tag version
      if: ${{ steps.versions.outputs.cli != steps.versions.outputs.current }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'release' }}

    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $CONTAINER_REGISTRY_HOST -u $CI_REPOSITORY_OWNER --password-stdin

      - name: Set build variables
        id: build
        run: |
          BRANCH=$(echo ${GITHUB_REF#refs/heads/})

          IMAGE_ID=$CONTAINER_REGISTRY_HOST/$CI_REPOSITORY_OWNER/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=$(curl https://api.github.com/repos/github/codeql-cli-binaries/releases/latest | jq -r '.tag_name' | sed -e 's/^v//')

          echo BRANCH=$BRANCH
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          echo ::set-output name=branch::${BRANCH}
          echo ::set-output name=image_id::${IMAGE_ID}
          echo ::set-output name=version::${VERSION}

      - name: Fetch cached image
        run: >-
          docker pull ${{ steps.build.outputs.image_id }}:${{ steps.build.outputs.version }} || true

      - name: Build image
        run: >-
          docker build .
          --file Dockerfile
          --tag $IMAGE_NAME
          --cache-from ${{ steps.build.outputs.image_id }}:${{ steps.build.outputs.version }}
          --label "org.opencontainers.image.revision=$GITHUB_SHA"
          --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}"
          --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          --label "com.github.repo.dockerfile=Dockerfile"
          --label "com.github.repo.branch=${{ steps.build.outputs.branch }}"
          --build-arg CLI_VERSION=${{ steps.build.outputs.version }}

      - name: Push image
        run: |
          docker tag $IMAGE_NAME ${{ steps.build.outputs.image_id }}:${{ steps.build.outputs.version }}
          docker push ${{ steps.build.outputs.image_id }}:${{ steps.build.outputs.version }}