name: Schedule

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get latest versions
      id: versions
      run: |
        CLI_RELEASE=$(curl https://api.github.com/repos/github/codeql-cli-binaries/releases/latest | jq -r '.tag_name')
        CURRENT_RELEASE=$(curl https://api.github.com/repos/nealfennimore/codeql-docker/releases/latest | jq -r '.tag_name')
        echo "::set-output name=cli::$CLI_RELEASE"
        echo "::set-output name=current::$CURRENT_RELEASE"
      shell: bash

    - name: Create Release
      if: ${{ steps.versions.outputs.cli != steps.versions.outputs.current }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.versions.outputs.cli }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}